# LAB

# Task 1 

Create a 1D array of integers from 1 to 20. Reshape it into a 4x5 2D array, 
then replace all elements in the last column with zeros. Finally, flatten the 
array back to 1D and print the result.


In [3]:
import numpy as np

arr1 = np.arange(1, 21)
arr2 = arr1.reshape(4, 5)

arr2[:, -1] = 0

flat = arr2.flatten()
print("Flattened array:", flat)


Flattened array: [ 1  2  3  4  0  6  7  8  9  0 11 12 13 14  0 16 17 18 19  0]


# task 2

 Generate a 2D array of random integers between 10 and 50 with a shape of 
5x5. Calculate and print the mean, sum, minimum, and maximum values for 
each row and each column separately

In [4]:
arr = np.random.randint(10, 50, (5, 5))
print("Array:\n", array_5x5)

row_means = arr.mean(axis=1)
row_sums = arr.sum(axis=1)
row_mins = arr.min(axis=1)
row_maxs = arr.max(axis=1)

col_means = arr.mean(axis=0)
col_sums = arr.sum(axis=0)
col_mins = arr.min(axis=0)
col_maxs = arr.max(axis=0)

print("\nRow Means:", row_means)
print("Row Sums:", row_sums)
print("Row Minimums:", row_mins)
print("Row Maximums:", row_maxs)
print("\nColumn Means:", col_means)
print("Column Sums:", col_sums)
print("Column Minimums:", col_mins)
print("Column Maximums:", col_maxs)


Array:
 [[33 14 17 18 18]
 [17 40 48 30 19]
 [23 16 35 23 35]
 [16 18 31 41 21]
 [10 13 23 23 13]]

Row Means: [20.  30.8 26.4 25.4 16.4]
Row Sums: [100 154 132 127  82]
Row Minimums: [14 17 16 16 10]
Row Maximums: [33 48 35 41 23]

Column Means: [19.8 20.2 30.8 27.  21.2]
Column Sums: [ 99 101 154 135 106]
Column Minimums: [10 13 17 18 13]
Column Maximums: [33 40 48 41 35]


# task 3

 Create an identity matrix of size 4x4. Add a constant (e.g., 5) to each 
element in the diagonal, and then replace the last row with a row of ones. 
Print the final matrix.



In [5]:
import numpy as np

identity_matrix = np.eye(4)
identity_matrix += np.diag([5] * 4)
identity_matrix[-1, :] = 1
print("Task 3 - Modified Identity Matrix:\n", identity_matrix)


Task 3 - Modified Identity Matrix:
 [[6. 0. 0. 0.]
 [0. 6. 0. 0.]
 [0. 0. 6. 0.]
 [1. 1. 1. 1.]]


# Task 4

Generate a 1D array of 15 random integers between 0 and 20. Count and 
display the number of occurrences of each unique value in the array, and list 
the indices of elements greater than 10.

In [6]:
random_array_1d = np.random.randint(0, 21, size=15)
unique_values, counts = np.unique(random_array_1d, return_counts=True)
indices_greater_than_10 = np.where(random_array_1d > 10)[0]
print("Task 4 - Random Array and Counts:")
print("Array:", random_array_1d)
print("Unique Value Counts:", dict(zip(unique_values, counts)))
print("Indices of elements greater than 10:", indices_greater_than_10)

Task 4 - Random Array and Counts:
Array: [18  6 11  1  8 18  6 14 19  7  2  5  8  7 20]
Unique Value Counts: {np.int32(1): np.int64(1), np.int32(2): np.int64(1), np.int32(5): np.int64(1), np.int32(6): np.int64(2), np.int32(7): np.int64(2), np.int32(8): np.int64(2), np.int32(11): np.int64(1), np.int32(14): np.int64(1), np.int32(18): np.int64(2), np.int32(19): np.int64(1), np.int32(20): np.int64(1)}
Indices of elements greater than 10: [ 0  2  5  7  8 14]


# Task 5

Create a 3x4 array filled with random floating-point numbers between 0 and 
1. Round each element to two decimal places, replace the elements in the 
second column with 0.5, and print the modified array.


In [7]:
import numpy as np
float_array = np.random.rand(3, 4)
float_array = np.round(float_array, 2)
float_array[:, 1] = 0.5
print("Modified Array:\n", float_array)


Modified Array:
 [[0.28 0.5  0.02 0.94]
 [0.29 0.5  0.11 0.22]
 [0.67 0.5  0.91 0.65]]
